<a href="https://colab.research.google.com/github/abhijadhav14/PythonPractice/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Single Dimensional

In [ ]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
print(n1)

[10 20 30 40]


In [ ]:
print(n1[2])

30


In [ ]:
type(n1)

numpy.ndarray

Multi-Dimensional


In [ ]:
n2=np.array([[10,30,50],[20,40,60]])
n2

array([[10, 30, 50],
       [20, 40, 60]])

In [ ]:
print(n2)

[[10 30 50]
 [20 40 60]]


In [ ]:
type(n2)

numpy.ndarray

zero Matrix

In [ ]:
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

In [ ]:
type(n3)

numpy.ndarray

In [ ]:
n4 = np.zeros((3,3))
n4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Full Matrix

In [ ]:
n5 = np.full((2,2),14)
n5

array([[14, 14],
       [14, 14]])

Range (arange)


In [ ]:
n6 = np.arange(1,10)
n6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
n7 = np.arange(5,50,5)
n7

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

Random

In [ ]:
n8 = np.random.randint(1,100,6)
n8

array([46, 72, 90, 31,  4, 18])

Shape

In [ ]:
n9 = np.array([[1,2,3],[4,5,6]])
n9.shape


(2, 3)

In [ ]:
n9.shape = (3,2)
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

Joining arrays
Stack

In [ ]:
n11 = np.array([1,2,3])
n12 = np.array([4,5,6])
n11

array([1, 2, 3])

In [ ]:
n12

array([4, 5, 6])

In [ ]:
np.vstack((n11,n12))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((n11,n12))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.column_stack((n11,n12))

array([[1, 4],
       [2, 5],
       [3, 6]])

Intersect and Difference

In [ ]:
n13 = np.array([10,20,30,40])
n13


array([10, 20, 30, 40])

In [ ]:
n14 = np.array([40,20,50,60])
n14

array([40, 20, 50, 60])

In [ ]:
np.intersect1d(n13,n14)

array([20, 40])

In [ ]:
np.setdiff1d(n13,n14)

array([10, 30])

In [ ]:
np.setdiff1d(n14,n13)

array([50, 60])

**Maths**

add


In [ ]:
np.sum([n13,n14])

270

In [ ]:
np.sum([n13,n14],axis=0)

array([ 50,  40,  80, 100])

In [ ]:
np.sum([n13,n14],axis=1)

array([100, 170])

In [ ]:
np.mean([n13])

25.0

In [ ]:
np.median([n13])

25.0

In [ ]:
np.std([n13])

11.180339887498949